server {
    listen 80;
    server_name localhost;
    
    location / {
        root   html;
        index  index.html;
        try_files $uri $uri/ =404;
    }
    
    location /status {
        return 200 '{"status": "running", "container": "nginx", "project": "unylea-devops"}';
        add_header Content-Type application/json;
    }
    
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root   html;
    }
}