# Inventory Ansible para Vagrant
[windows]
192.168.56.10 ansible_user=vagrant ansible_password=Unylea@2024!DevOps ansible_connection=winrm ansible_winrm_server_cert_validation=ignore ansible_winrm_transport=basic ansible_port=5985

[windows:vars]
ansible_user=vagrant
ansible_password=Unylea@2024!DevOps
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_port=5985
