[windows]
# PREENCHER COM O IP PUBLICO DA VM AZURE APOS TERRAFORM APPLY
# Exemplo: 20.123.45.67
# <IP_PUBLICO> ansible_user=azureuser ansible_password=Unylea@2024!AzureDevOps

[windows:vars]
ansible_user=azureuser
ansible_password=Unylea@2024!AzureDevOps
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_port=5985
ansible_winrm_scheme=http
