[windows]
# PREENCHER COM O IP PUBLICO DA INSTANCIA APOS TERRAFORM APPLY
# Exemplo: 203.0.113.10
# <IP_PUBLICO> ansible_user=Administrator ansible_password=Unylea@2024!DevOps

[windows:vars]
ansible_user=Administrator
ansible_password=Unylea@2024!DevOps
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_port=5986
ansible_winrm_scheme=https
