# Inventory Ansible para Azure Professional
[windows]
{{ vm_public_ip }} ansible_user=azureuser ansible_password=Unylea@2024!DevOps ansible_connection=winrm ansible_winrm_server_cert_validation=ignore ansible_winrm_transport=basic ansible_port=5985

[windows:vars]
ansible_user=azureuser
ansible_password=Unylea@2024!DevOps
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=basic
ansible_port=5985
ansible_winrm_scheme=http
